import Header from "@/components/Header/Header";
import Sidebar from "@/components/Sidebar/Sidebar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`flex items-start justify-between`}>
        <Sidebar />
        <main className="grid h-full pl-[300px]" style={{
          width: 'calc(100% - 0px)'
        }}>
          <Header />
          <div className="p-8">{children}</div>
        </main>
      </body>
    </html>
  );
}
